from .jihua_task import JihuaTask
from .dig_task_v2 import DigTaskV2
from .zhaoxi_task import ZhaoxiTask
from .bless_task import BlessTask
from .monster_task import MonsterTask
from .all_in_one_task import AllInOneTask
from .monthly_pass_task import MonthlyPassTask
from .weekly_realm_task import WeeklyRealmTask
from .xinghai_task import XinghaiTask